### ISSUE TITLE
Fix the Github actions pipeline

### ISSUE THREAD

**Issue by PawanRamaMali** [PawanRamaMali/edgemodelr#6]

**Comment by eddelbuettel** [comment]
Sorry, I had not seen that you had merged my quick test and check.  The default ci.yaml I copy around between my repos does not (by default) show the logs (as I had not needed that often).  But when something fails that is a hindrance.  

You can simply add this block I use in a few repos:

```yaml
      - name: Dump logs
        if: always()
        run: ./run.sh dump_logs
```

I will commit it to my fork too to be more explicit.

**Comment by PawanRamaMali** [comment]
No worries at all! Thanks for the explanation about the CI logs - that makes perfect sense. Having logs available when tests fail is definitely crucial for debugging.

Feel free to commit it to your fork whenever convenient. Thanks for taking the time to improve the CI setup!

**Comment by eddelbuettel** [comment]
I really love what you are doing here.  I think I will look into one angle of assistance, something I had done before for another repo:  have `configure` see and check if the external library exists, and use it.  Debian now has `llama.cpp` and `ggml` (with a selection of backends) so we can already do this in Docker using a Debian container; I should get these also with Ubuntu 25.10 when I update from 25.04 in a few weeks (release is always October, I commonly wait a few weeks ...)

I still haven't worked out if `llama.cpp` can use the `ollama` files.  Some load, but then produces ... gibberish?  I need to find some time to play some more, had been distracted by other stuff.

**Comment by PawanRamaMali** [comment]
Thanks! That makes perfect sense—compilation errors being hidden behind test failures is definitely frustrating when you're trying to debug CI issues. The three-liner should help surface those immediately when builds fail.

Your idea about detecting external llama.cpp/ggml libraries sounds great! Having a configure script that can use system packages when available would be much more elegant than bundling everything. That would also significantly reduce the package size.

Regarding ollama files - that's an interesting compatibility question. The format differences might explain the gibberish output. Definitely worth investigating !

**Comment by eddelbuettel** [comment]
Yes, I have actually been around 'making neat C++ libraries available to R' for what is now decades, and there are definitely two aspects.  I happen to think a 'both worlds' approach wins:  including the files as you do provides a good fallback and more universal coverage to 'whereever R builds'.  This has costs, both in setup as you now learn having to cover amd64 and arm64 on two different OSs (and eventually three, Windows will get arm64 too via Rtools IIRC) and of course in build time.  Using an external library where it exists is elegant, can be faster in both build and run-time but shifts the pain to the maintainers of R windows and mac ports and they then need the library.  Hybrid can get the best of both at some extra work.  

Detection is usually very cheap because of `pkgconf`. I just poked at the Debian package and it looks like it puts the .pc file in the wrong place so one has to add to the discovery path. When that is done you get link and compile flags:

```sh
root@3eaed7568463:/# pkgconf --with-path=/usr/lib/x86_64-linux-gnu/llama/pkgconfig/ --libs llama
-L/usr/lib/x86_64-linux-gnu/llama -lggml -lggml-base -lllama 
root@3eaed7568463:/# pkgconf --with-path=/usr/lib/x86_64-linux-gnu/llama/pkgconfig/ --cflags llama
-I/usr/include/llama 
root@3eaed7568463:/# 
```
